// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4V1RCUkHy-cHoemkSgwbWenTaQg53lS4',
    appId: '1:356943071344:web:af709cff4d3ffe0af24cb5',
    messagingSenderId: '356943071344',
    projectId: 'fanclub-app-2025',
    authDomain: 'fanclub-app-2025.firebaseapp.com',
    storageBucket: 'fanclub-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh977ywI7NBxx_Gpzfs3eJQMmdP34POXs',
    appId: '1:356943071344:android:0c37248631979926f24cb5',
    messagingSenderId: '356943071344',
    projectId: 'fanclub-app-2025',
    storageBucket: 'fanclub-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSI__DdX8YI1V2ItPlF2B4BXUD8hnhG9w',
    appId: '1:356943071344:ios:ee671ec867b0a132f24cb5',
    messagingSenderId: '356943071344',
    projectId: 'fanclub-app-2025',
    storageBucket: 'fanclub-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.fanclubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSI__DdX8YI1V2ItPlF2B4BXUD8hnhG9w',
    appId: '1:356943071344:ios:ee671ec867b0a132f24cb5',
    messagingSenderId: '356943071344',
    projectId: 'fanclub-app-2025',
    storageBucket: 'fanclub-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.fanclubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4V1RCUkHy-cHoemkSgwbWenTaQg53lS4',
    appId: '1:356943071344:web:db5168bf009dee3ff24cb5',
    messagingSenderId: '356943071344',
    projectId: 'fanclub-app-2025',
    authDomain: 'fanclub-app-2025.firebaseapp.com',
    storageBucket: 'fanclub-app-2025.firebasestorage.app',
  );
}
